[project]
name = "timekieu-app"
version = "1.0.0"
dependencies = [
    "streamlit>=1.28,<1.29",
    "pandas>=2.2,<2.3",
    "numpy>=1.26,<1.27",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
